config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'welcome/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    # @docs = Doc.all.order("created_at DESC")
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    # @doc = Doc.new
    @doc = current_user.docs.build
  end

  def create
    # @doc = Doc.new(doc_params)
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Fix Doc!

  = render 'form'

  = link_to "Cancel", docs_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)
    - else
      %h2 Create Doc!
      %p Start Creating Documents and Organizing your life!
      %button= link_to "Create Doc", new_doc_path

-# = link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc!

  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %p.title= @doc.title
    %p= simple_format(@doc.content)

    .buttons
      = link_to "Fix Doc", edit_doc_path(@doc), class: "button"
      = link_to "Trash it", doc_path(@doc), method: :delete,
       data: { confirm: "Are you sure?" }, class: "button"

app/views/layouts/application.html.haml
-#-#<!DOCTYPE html>
-#-#<html>
-#-#  <head>
-#-#    <title>Cabinet</title>
-#-#    <%= csrf_meta_tags %>
-#-#    <%= csp_meta_tag %>
-#-#
-#-#    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
-#-#    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
-#-#  </head>
-#-#
-#-#  <body>
-#-#
-#-#  <p class="notice"><%= notice %></p>
-#-#  <p class="alert"><%= alert %></p>
-#-#
-#-#  <%= yield %>
-#-#  </body>
-#-#</html>
-#
-#!!!
-#%html
-#%head
-#  %title FileCabinet | Your Life's Work!
-#  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
-#  = javascript_pack_tag 'application', 'data-turbolinks-track' => true
-#  = csrf_meta_tags
-#%body
-#  %header
-#    .header_inner
-#      = link_to "FileCabinet", root_path
-#
-#      %nav
-#        - if user_signed_in?
-#          = link_to "Create Doc", new_doc_path
-#          = link_to "Sign Out", destroy_user_session_path, method: :delete
-#        - else
-#          = link_to "Log In", new_user_session_path
-#
-#  %p.notice= notice
-#  %p.alert= alert
-#
-#  = yield
-#
-#

!!!
%html
%head
  %title FileCabinet | Your life's work!
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_pack_tag  'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: "logo"

      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign out", destroy_user_session_path, method: :delete

        - else
          = link_to "Log In", new_user_session_path

%p.notice= notice
%p.alert= alert

= yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Your life's work. Organized, always.
    %button= link_to "Enter", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.

#bottom_cta
  .wrapper
    %h3 Go Ahead!
    %br
    %button= link_to "Join Now", new_user_registration_path